### ISSUE TITLE
Dockerfile wrong name

### ISSUE THREAD

**Issue by pwnedshell** [R00tedSec/mazdabudgets#1]
The Dockerfile is named with an uppercase "F" ("DockerFile") and should be a lowercase ("Dockerfile")´.

![image](https://github.com/R00tedSec/mazdabudgets/assets/55540142/bccf6e49-4b77-48e7-8088-110127b66af6)

[Reference](https://stackoverflow.com/a/26084010).

**Comment by R00tedSec** [comment]
Applied change
